runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: triple-pottery-212308.appspot.com
#[END env]